### ISSUE TITLE
Broken pipe attempting usage as in README

### ISSUE THREAD

**Issue by 0xEVom** [hananbeer/master#1]
Hey, really digging the idea behind this tool, it seems like it could be a big help for auditing. Right now I would say it disrupts the workflow a bit too much, especially with the need to go back and forth between the two versions and/or recompile with different options depending on the file. But honestly I would 100% pay to have this functionality as a VS Code extension. Being able to inline functions as easily as collapsing sections of the code, inline `using...for` and delinearize with the click of a button etc. would be awesome.

I tried using the tool as in the README:

```
cat ./data/build.json |
python3 ./src/ast_patcher.py - shadow_block |
python3 ./src/ast_patcher.py - function_inliner -c LendingTerm -m borrow -d 2 |
python3 ./src/ast_patcher.py - using_for_inliner |
python3 ./src/ast_patcher.py - delinearizer -c LendingTerm |
sol-ast-compile --source --stdin --mode json
```

And got:

```
Unexpected end of JSON input
Traceback (most recent call last):
  File "[...]/master/./src/ast_patcher.py", line 54, in <module>
    print(json.dumps(data))
BrokenPipeError: [Errno 32] Broken pipe
```

The command seems to work fine until the last step. Without the last line, it outputs the expected JSON. I tried to save and compile the output separately, but that also failed:

```
> sol-ast-compile ./data.json --source --mode json
// ------------------------------------------------------------
// data/flat.sol
// ------------------------------------------------------------
Cannot read properties of undefined (reading 'vType')
```

**Comment by hananbeer** [comment]
hi, I appreciate the response.

please link to the flattened sol file or build json and I will have a look.

regarding extension: as far as I know there is no market for paid extensions. I am working on a web version, but don't get too excited as it's going to be free.

**Comment by 0xEVom** [comment]
Here's the [build.json](https://github.com/hananbeer/master/files/13749387/build.json). Thanks for taking a look!

I see, yeah that's a shame. Looking forward to the web version though.

**Comment by hananbeer** [comment]
the function inliner tried to inline an external function from another contract.
while it can actually do that, it probably shouldn't since it's a different context entirely.
`sol-ast-compile` did not know how to rebuild that AST. now it works fine.

note to self: in the future it would be nice to inline public functions if they are of the same contract & not performing an actual `CALL`.

pull the fix and let me know what you think of the produced output now.

**Comment by 0xEVom** [comment]
Fixed, thanks!
